---
# jobs for app env
- name: setup APP instance
  include: app_setup.yml
  tags:
    - apache-php-configuration

- name: setup DB instance
  include: db_setup.yml
  tags:
    - mysql-configuration

- name: deploy site
  include: site_deploy.yml
  tags:
    - site-deploy